// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type RequestLoginCode struct {
	Email string `json:"email"`
}

type ValidateLoginCode struct {
	Code string `json:"code"`
}
